import 'katex/dist/katex.min.css';
import { syntaxTree } from '@codemirror/language';
import {
  Decoration,
  type DecorationSet,
  EditorView,
  WidgetType,
} from '@codemirror/view';
import { type Extension, type Range, StateField } from '@codemirror/state';
import type { EditorState } from '@codemirror/state';
import katex from 'katex';

/** Cache rendered HTML keyed by LaTeX source + display mode. */
const htmlCache = new Map<string, string>();

/**
 * Render LaTeX to HTML using KaTeX with caching.
 * Returns an HTML string (may be an error message styled by KaTeX).
 */
function renderMath(latex: string, displayMode: boolean): string {
  const cacheKey = `${displayMode ? 'D' : 'I'}:${latex}`;
  const cached = htmlCache.get(cacheKey);
  if (cached !== undefined) return cached;

  const html = katex.renderToString(latex, {
    throwOnError: false,
    displayMode,
  });
  htmlCache.set(cacheKey, html);
  return html;
}

/**
 * Clear the KaTeX render cache. Useful for testing.
 */
export function clearMathCache(): void {
  htmlCache.clear();
}

/**
 * Safely set KaTeX-rendered HTML by parsing it through the DOMParser
 * and importing only valid nodes into the document.
 * KaTeX output is trusted (generated by the library, not user input),
 * but we use DOM parsing as a defense-in-depth measure.
 */
function setMathContent(container: HTMLElement, html: string): void {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const body = doc.body;

  // Import all child nodes from the parsed HTML into our document
  while (body.firstChild) {
    const imported = document.importNode(body.firstChild, true);
    container.appendChild(imported);
    body.removeChild(body.firstChild);
  }
}

// ─── Inline math widget ($...$) ────────────────────────────────────────────

class InlineMathWidget extends WidgetType {
  constructor(private latex: string) {
    super();
  }

  toDOM(): HTMLElement {
    const span = document.createElement('span');
    span.className = 'cm-math-inline';
    setMathContent(span, renderMath(this.latex, false));
    return span;
  }

  eq(other: InlineMathWidget): boolean {
    return this.latex === other.latex;
  }

  get estimatedHeight(): number {
    return -1; // inline
  }
}

// ─── Display math widget ($$...$$) ─────────────────────────────────────────

class DisplayMathWidget extends WidgetType {
  constructor(private latex: string) {
    super();
  }

  toDOM(): HTMLElement {
    const div = document.createElement('div');
    div.className = 'cm-math-display';
    setMathContent(div, renderMath(this.latex, true));
    return div;
  }

  eq(other: DisplayMathWidget): boolean {
    return this.latex === other.latex;
  }
}

// ─── Regex-based math detection ────────────────────────────────────────────

interface MathMatch {
  from: number; // Start of the entire delimiter + content
  to: number; // End of the entire delimiter + content
  latex: string; // The LaTeX source (without delimiters)
  display: boolean; // true = display mode ($$), false = inline ($)
}

/**
 * Collect all ranges inside FencedCode and InlineCode nodes so we can
 * skip dollar signs inside code spans and code blocks.
 */
function collectCodeRanges(state: EditorState): Array<{ from: number; to: number }> {
  const ranges: Array<{ from: number; to: number }> = [];
  syntaxTree(state).iterate({
    enter(node) {
      if (node.name === 'FencedCode' || node.name === 'InlineCode') {
        ranges.push({ from: node.from, to: node.to });
      }
    },
  });
  return ranges;
}

/**
 * Check whether a given position falls inside any of the code ranges.
 */
function isInsideCode(pos: number, codeRanges: Array<{ from: number; to: number }>): boolean {
  for (const range of codeRanges) {
    if (pos >= range.from && pos < range.to) return true;
  }
  return false;
}

/**
 * Scan the document text for $...$ and $$...$$ math delimiters.
 *
 * Rules:
 * - `\$` is an escaped dollar sign, not a delimiter
 * - `$$...$$` is display math (block-level)
 * - `$...$` is inline math; the opening $ must NOT be followed by a space,
 *   and the closing $ must NOT be preceded by a space
 * - Dollar signs inside code spans/blocks are ignored
 * - Standalone `$` (e.g., "$100") are not treated as math
 */
function findMathRanges(state: EditorState): MathMatch[] {
  const doc = state.doc;
  const text = doc.sliceString(0);
  const codeRanges = collectCodeRanges(state);
  const matches: MathMatch[] = [];

  let i = 0;
  while (i < text.length) {
    // Skip escaped dollar signs
    if (text[i] === '\\' && i + 1 < text.length && text[i + 1] === '$') {
      i += 2;
      continue;
    }

    if (text[i] !== '$') {
      i++;
      continue;
    }

    // Skip if inside a code block/span
    if (isInsideCode(i, codeRanges)) {
      i++;
      continue;
    }

    // Check for display math: $$...$$
    if (i + 1 < text.length && text[i + 1] === '$') {
      // Display math requires $$ at the start of a line (only whitespace before it)
      const lineStart = text.lastIndexOf('\n', i - 1) + 1; // 0 if no preceding newline
      const textBeforeOnLine = text.slice(lineStart, i);
      if (textBeforeOnLine.trim().length > 0) {
        // $$ is mid-line — skip display math entirely; inline $ handling won't
        // match $$ so we just advance past these two characters
        i += 2;
        continue;
      }

      const start = i;
      const contentStart = i + 2;
      // Find closing $$
      let j = contentStart;
      let found = false;
      while (j < text.length - 1) {
        if (text[j] === '\\' && j + 1 < text.length && text[j + 1] === '$') {
          j += 2;
          continue;
        }
        if (text[j] === '$' && text[j + 1] === '$') {
          const latex = text.slice(contentStart, j);
          if (latex.length > 0) {
            matches.push({
              from: start,
              to: j + 2,
              latex,
              display: true,
            });
          }
          i = j + 2;
          found = true;
          break;
        }
        j++;
      }
      if (!found) {
        // No closing $$, skip these two dollar signs
        i += 2;
      }
      continue;
    }

    // Check for inline math: $...$
    const start = i;
    const contentStart = i + 1;

    // Opening $ must not be followed by a space or another $
    if (contentStart >= text.length || text[contentStart] === ' ' || text[contentStart] === '$') {
      i++;
      continue;
    }

    // Find closing $
    let j = contentStart;
    let found = false;
    while (j < text.length) {
      if (text[j] === '\\' && j + 1 < text.length && text[j + 1] === '$') {
        j += 2;
        continue;
      }
      // Inline math doesn't span multiple lines
      if (text[j] === '\n') {
        break;
      }
      if (text[j] === '$') {
        // Closing $ must not be preceded by a space
        if (j > contentStart && text[j - 1] !== ' ') {
          const latex = text.slice(contentStart, j);
          // Ensure content is non-empty and not just whitespace
          if (latex.trim().length > 0) {
            matches.push({
              from: start,
              to: j + 1,
              latex,
              display: false,
            });
          }
          i = j + 1;
          found = true;
          break;
        }
        break; // space before closing $, not valid inline math
      }
      j++;
    }
    if (!found) {
      i++;
    }
  }

  return matches;
}

// ─── Decoration builder ────────────────────────────────────────────────────

function buildMathDecorations(state: EditorState): DecorationSet {
  const decorations: Range<Decoration>[] = [];

  // Determine which lines the cursor is on
  const cursorLines = new Set<number>();
  for (const range of state.selection.ranges) {
    const startLine = state.doc.lineAt(range.from).number;
    const endLine = state.doc.lineAt(range.to).number;
    for (let l = startLine; l <= endLine; l++) {
      cursorLines.add(l);
    }
  }

  const mathRanges = findMathRanges(state);

  for (const m of mathRanges) {
    // Check if cursor is on any line spanned by this math region
    const startLine = state.doc.lineAt(m.from).number;
    const endLine = state.doc.lineAt(m.to - 1).number;
    let cursorInside = false;
    for (let l = startLine; l <= endLine; l++) {
      if (cursorLines.has(l)) {
        cursorInside = true;
        break;
      }
    }
    if (cursorInside) continue;

    if (m.display) {
      // Display math: replace the entire $$...$$ with a block widget
      decorations.push(
        Decoration.replace({
          widget: new DisplayMathWidget(m.latex),
          block: true,
        }).range(m.from, m.to),
      );
    } else {
      // Inline math: replace $...$ with rendered inline widget
      decorations.push(
        Decoration.replace({
          widget: new InlineMathWidget(m.latex),
        }).range(m.from, m.to),
      );
    }
  }

  // Sort by position (required by RangeSet)
  decorations.sort((a, b) => a.from - b.from);

  return Decoration.set(decorations);
}

// ─── StateField ────────────────────────────────────────────────────────────

/**
 * StateField that provides math widget decorations.
 * Uses StateField instead of ViewPlugin because display math with block: true
 * requires a StateField in CM6.
 */
const mathField = StateField.define<DecorationSet>({
  create(state) {
    return buildMathDecorations(state);
  },
  update(value, tr) {
    if (tr.docChanged || tr.selection || tr.effects.length > 0) {
      return buildMathDecorations(tr.state);
    }
    return value;
  },
  provide(field) {
    return EditorView.decorations.from(field);
  },
});

// ─── Styles ────────────────────────────────────────────────────────────────

const mathStyles = EditorView.baseTheme({
  '.cm-math-inline': {
    display: 'inline',
    verticalAlign: 'baseline',
  },
  '.cm-math-inline .katex': {
    fontSize: '1em',
  },
  '.cm-math-display': {
    display: 'flex',
    justifyContent: 'center',
    padding: '8px 0',
    overflow: 'auto',
  },
  '.cm-math-display .katex-display': {
    margin: '0',
  },
  // KaTeX error styling
  '.cm-math-inline .katex-error': {
    color: '#ef4444',
    fontSize: '0.85em',
  },
  '.cm-math-display .katex-error': {
    color: '#ef4444',
    fontSize: '0.85em',
    fontStyle: 'italic',
  },
});

// ─── Export ─────────────────────────────────────────────────────────────────

export const mathWidget: Extension = [
  mathField,
  mathStyles,
];
